exec:
  max_threads: 8
  min_output_tasks: 1
in:
  type: file
  path_prefix: ./csv/
  parser:
    type: csv
    columns:
    - {name: name, type: string}

out:
  type: mysql
  user: root
  host: mysql
  port: 3306
  database: test
  table: users
  mode: merge_direct
  retry_limit: 1
