version: "3.7"

services:
  embulk:
    build: .
    networks:
      - default

  mysql:
    image: mysql:5.7.25
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - default

networks:
  default:
